baseurl:
name: Movimento dos Trabalhadores Rurais Sem Terra
description: "Há 29 anos, em Cascavel (PR), centenas de trabalhadores rurais decidiram fundar um movimento social camponês, autônomo, que lutasse pela terra, pela Reforma Agrária e pelas transformações sociais necessárias para o nosso país. Eram posseiros, atingidos por barragens, migrantes, meeiros, parceiros e pequenos agricultores"
markdown: redcarpet
url: http://www.mst.org.br
antigo: //antigo.mst.org.br
asset_pipeline:
  gzip: true
facebook: 784439748288439
sass:
  style: :compressed
collections:
  banners:
timezone: BR
lollipop:
  title: Nossa História
  link: nossa-historia
  enabled: true
gems:
  - jekyll-sitemap
  - jekyll-paginate-by
exclude:
  - deploy
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - README.md
  - bower_components
  - node_modules
  - package.json
  - assets/less
  - test
  - Rakefile
  - job_status.txt
  - setup
  - vendor
  - node/
  - templates/
  - skelleton.json
paginate_by:
  options:
    template: "_templates/news"
    per_page: 15
    page_link: ":num"
    pages_limit: 15
  filters:
    - section:
        permalink: "videos"
        per_page: 9
        template: "_templates/videos"
        only:
          - section: "tv"
