paginate: 20
baseurl:
paginate_path: "/:dir_name/page:num"
paginate_layout: "/noticias"
name: Movimento dos Trabalhadores Rurais Sem Terra
markdown: redcarpet
url: http://novo.mst.org.br
asset_pipeline:
  gzip: true
facebook: 784439748288439
sass:
  style: :compressed
collections:
  banners:
timezone: BR
gems:
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - deploy
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - README.md
  - bower_components
  - node_modules
  - package.json
  - assets/less
  - test
  - Rakefile
  - job_status.txt
  - setup
  - vendor
  - node/
