paginate: 20
baseurl: 
paginate_path: "/noticias/page:num"
name: Movimento dos Trabalhadores Rurais Sem Terra
markdown: redcarpet
url: http://localhost:4000
asset_pipeline:
  gzip: true
facebook: 1542469885974977
sass:
  style: :compressed
collections:
  banners:
timezone: BR
gems:
  - jekyll-sitemap
exclude:
  - deploy
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - README.md
  - bower_components
  - node_modules
  - package.json
  - assets/less
  - test
  - Rakefile
  - job_status.txt
  - setup
  - vendor 
  - node/
